#!/usr/bin/env python3
"""Regenerate .rnd/index.json, .rnd/INDEX.md and .rnd/knowledge/catalog.json from the case files.

  python3 .claude/scripts/generate_index.py [--quiet] [--check]

--check exits 2 when the committed index differs from what would be generated.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rndlib  # noqa: E402
from rndlib import KNOWLEDGE_DIR, RND_DIR, RND_ROOT, now_iso, read_json, rel, write_json, write_text  # noqa: E402


def parse_frontmatter(text: str) -> dict:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    meta: dict = {}
    if not m:
        return meta
    for line in m.group(1).splitlines():
        k, sep, v = line.partition(":")
        if not sep:
            continue
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            meta[k.strip()] = [x.strip().strip("'\"") for x in v[1:-1].split(",") if x.strip()]
        else:
            meta[k.strip()] = v.strip("'\"")
    return meta


def build_case_index() -> dict:
    cases = []
    for d in rndlib.case_dirs():
        try:
            c = read_json(d / "case.json")
        except Exception as exc:  # noqa: BLE001
            rndlib.eprint(f"warning: skipping {d.name}: {exc}")
            continue
        cases.append({
            "id": c["id"], "slug": c["slug"], "dir": rel(d), "title": c["title"], "state": c["state"],
            "caseType": c["caseType"], "riskLevel": c["riskLevel"], "tags": c.get("tags", []), "keywords": c.get("keywords", []),
            "freshnessClass": c.get("freshnessClass"), "created": c["created"], "updated": c["updated"],
            "targetRepository": c.get("targetRepository"), "relatedCases": c.get("relatedCases", []),
            "decision": {"outcome": c["decision"].get("outcome"), "summary": c["decision"].get("summary", "")},
            "review": {"status": c["review"]["status"], "rounds": c["review"]["rounds"]},
            "validation": c["validation"]["status"],
            "nextAction": c.get("nextAction", ""),
        })
    return {"schemaVersion": 1, "engineVersion": rndlib.engine_version(), "generatedAt": now_iso(), "count": len(cases), "cases": cases}


def build_index_md(idx: dict) -> str:
    active = [c for c in idx["cases"] if c["state"] != "ARCHIVED"]
    archived = [c for c in idx["cases"] if c["state"] == "ARCHIVED"]
    lines = ["# R&D Case Index", "", f"_Generated by `.claude/scripts/generate_index.py` - {idx['count']} case(s). Do not edit by hand._", ""]

    def table(rows: list[dict]) -> list[str]:
        out = ["| ID | State | Type | Risk | Title | Tags | Decision | Updated |", "|----|-------|------|------|-------|------|----------|---------|"]
        for c in rows:
            out.append(f"| [{c['id']}]({c['dir'].split('/', 1)[1] if c['dir'].startswith('.rnd/') else c['dir']}/case.json) | {c['state']} | {c['caseType']} | {c['riskLevel']} | {c['title']} | {', '.join(c['tags'])} | {c['decision']['outcome'] or ''} | {c['updated'][:10]} |")
        return out

    lines += ["## Active", ""] + (table(active) if active else ["(none)"]) + [""]
    lines += ["## Archived", ""] + (table(archived) if archived else ["(none)"]) + [""]
    tags: dict[str, list[str]] = {}
    for c in idx["cases"]:
        for t in c["tags"]:
            tags.setdefault(t, []).append(c["id"])
    if tags:
        lines += ["## Tags", ""] + [f"- **{t}**: {', '.join(ids)}" for t, ids in sorted(tags.items())] + [""]
    return "\n".join(lines)


def build_catalog() -> dict:
    entries = []
    for bucket in ("shared", "candidates"):
        bdir = KNOWLEDGE_DIR / bucket
        if not bdir.exists():
            continue
        for p in sorted(bdir.rglob("*.md")):
            meta = parse_frontmatter(p.read_text(encoding="utf-8", errors="ignore"))
            entries.append({
                "path": rel(p), "bucket": bucket,
                "title": meta.get("title") or p.stem, "tags": meta.get("tags", []) if isinstance(meta.get("tags"), list) else [],
                "sourceCases": meta.get("sourceCases", []) if isinstance(meta.get("sourceCases"), list) else ([meta["sourceCases"]] if meta.get("sourceCases") else []),
                "freshnessClass": meta.get("freshnessClass", "normal"), "lastVerified": meta.get("lastVerified"),
                "promotedAt": meta.get("promotedAt"), "status": meta.get("status", bucket),
            })
    return {"schemaVersion": 1, "generatedAt": now_iso(), "count": len(entries), "entries": entries}


def _strip_generated(d: dict) -> dict:
    # metadata that changes without the case content changing must not make the
    # index look stale (an engine version bump is not a reason to regenerate)
    return {k: v for k, v in d.items() if k not in ("generatedAt", "engineVersion")}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    RND_DIR.mkdir(parents=True, exist_ok=True)
    idx = build_case_index()
    cat = build_catalog()
    if a.check:
        cur_idx = read_json(RND_ROOT / "index.json", {})
        cur_cat = read_json(KNOWLEDGE_DIR / "catalog.json", {})
        if _strip_generated(cur_idx) != _strip_generated(idx) or _strip_generated(cur_cat) != _strip_generated(cat):
            print("index out of date: run python3 .claude/scripts/generate_index.py")
            return 2
        print("index up to date")
        return 0
    write_json(RND_ROOT / "index.json", idx)
    write_text(RND_ROOT / "INDEX.md", build_index_md(idx))
    write_json(KNOWLEDGE_DIR / "catalog.json", cat)
    if not a.quiet:
        print(f"{rel(RND_ROOT / 'index.json')}: {idx['count']} case(s); {rel(KNOWLEDGE_DIR / 'catalog.json')}: {cat['count']} entr(ies)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
